import { prisma, logSection, logCount } from "./client";

export async function seedSources() {
  logSection("Research Sources");

  const sources = [
    {
      slug: "neumann-kinesiology-2017",
      title: "Kinesiology of the Musculoskeletal System: Foundations for Rehabilitation",
      authors: "Neumann DA",
      year: 2017,
      sourceType: "textbook",
      description: "Comprehensive kinesiology textbook widely used in PT education. Covers detailed musculoskeletal anatomy and biomechanics.",
      confidence: 0.95,
    },
    {
      slug: "kendall-muscles-2005",
      title: "Muscles: Testing and Function with Posture and Pain",
      authors: "Kendall FP, McCreary EK, Provance PG, Rodgers MM, Romani WA",
      year: 2005,
      sourceType: "textbook",
      description: "Classic reference for manual muscle testing, muscle anatomy, and postural assessment.",
      confidence: 0.9,
    },
    {
      slug: "magee-orthopedic-2014",
      title: "Orthopedic Physical Assessment",
      authors: "Magee DJ",
      year: 2014,
      sourceType: "textbook",
      description: "Standard reference for orthopedic assessment techniques and clinical reasoning in PT.",
      confidence: 0.9,
    },
    {
      slug: "kisner-therapeutic-2017",
      title: "Therapeutic Exercise: Foundations and Techniques",
      authors: "Kisner C, Colby LA, Borstad J",
      year: 2017,
      sourceType: "textbook",
      description: "Foundational text on therapeutic exercise prescription, progressions, and clinical application.",
      confidence: 0.9,
    },
    {
      slug: "acsm-guidelines-2021",
      title: "ACSM's Guidelines for Exercise Testing and Prescription",
      authors: "American College of Sports Medicine",
      year: 2021,
      sourceType: "guideline",
      description: "Evidence-based guidelines for exercise prescription across healthy and clinical populations.",
      confidence: 0.9,
    },
    // ── Region-Based Exercise Evidence Sources ────────────────────────────
    // Cervical Spine
    {
      slug: "sun-cervicothoracic-2024",
      title: "Effects of Exercise Combined With Cervicothoracic Spine Self-Mobilization on Chronic Non-Specific Neck Pain",
      authors: "Sun X, Chai L, Huang Q, Zhou H, Liu H",
      year: 2024,
      journal: "Scientific Reports",
      sourceType: "journal",
      description: "RCT showing combined cervical and thoracic self-mobilization exercises improve chronic neck pain outcomes superior to cervical-only interventions.",
      confidence: 0.85,
    },
    {
      slug: "gross-neck-exercises-2015",
      title: "Exercises for Mechanical Neck Disorders",
      authors: "Gross A, Kay TM, Paquin JP, et al.",
      year: 2015,
      journal: "The Cochrane Database of Systematic Reviews",
      sourceType: "journal",
      description: "Cochrane systematic review of exercise interventions for mechanical neck disorders. Supports cervico-scapulothoracic strengthening.",
      confidence: 0.95,
    },
    {
      slug: "amiri-arimi-deep-flexors-2017",
      title: "The Effect of Different Exercise Programs on Size and Function of Deep Cervical Flexor Muscles in Patients With Chronic Nonspecific Neck Pain: A Systematic Review of Randomized Controlled Trials",
      authors: "Amiri Arimi S, Mohseni Bandpei MA, Javanshir K, Rezasoltani A, Biglarian A",
      year: 2017,
      journal: "American Journal of Physical Medicine & Rehabilitation",
      sourceType: "journal",
      description: "Systematic review of RCTs showing exercise programs improve deep cervical flexor size and function in chronic neck pain.",
      confidence: 0.9,
    },
    {
      slug: "moon-cervical-muscle-2021",
      title: "Effects of Exercise on Cervical Muscle Strength and Cross-Sectional Area in Patients With Thoracic Hyperkyphosis and Chronic Cervical Pain",
      authors: "Moon H, Lee SK, Kim WM, Seo YG",
      year: 2021,
      journal: "Scientific Reports",
      sourceType: "journal",
      description: "Exercise improves cervical muscle strength and cross-sectional area in patients with thoracic hyperkyphosis and chronic cervical pain.",
      confidence: 0.8,
    },
    {
      slug: "mueller-neck-dose-response-2023",
      title: "Resistance, Motor Control, and Mindfulness-Based Exercises Are Effective for Treating Chronic Nonspecific Neck Pain: A Systematic Review With Meta-Analysis and Dose-Response Meta-Regression",
      authors: "Mueller J, Weinig J, Niederer D, Tenberg S, Mueller S",
      year: 2023,
      journal: "The Journal of Orthopaedic and Sports Physical Therapy",
      sourceType: "journal",
      description: "Systematic review with dose-response meta-regression supporting 2-3 sessions/week for chronic neck pain. Supports resistance and motor control exercises.",
      confidence: 0.9,
    },
    // Thoracic Spine
    {
      slug: "cho-thoracic-vs-cervical-2017",
      title: "Upper Thoracic Spine Mobilization and Mobility Exercise Versus Upper Cervical Spine Mobilization and Stabilization Exercise in Individuals With Forward Head Posture: A Randomized Clinical Trial",
      authors: "Cho J, Lee E, Lee S",
      year: 2017,
      journal: "BMC Musculoskeletal Disorders",
      sourceType: "journal",
      description: "RCT showing thoracic mobilization is more effective than cervical-only intervention for forward head posture.",
      confidence: 0.85,
    },
    {
      slug: "ozdemir-schroth-2023",
      title: "A Randomized Controlled Study of the Effect of Functional Exercises on Postural Kyphosis: Schroth-Based Three-Dimensional Exercises Versus Postural Corrective Exercises",
      authors: "Özdemir Görgü S, Algun ZC",
      year: 2023,
      journal: "Disability and Rehabilitation",
      sourceType: "journal",
      description: "RCT demonstrating large effect sizes for Schroth exercises on kyphosis reduction (14.76° mean), lumbar lordosis, balance, and quality of life.",
      confidence: 0.85,
    },
    {
      slug: "feng-kyphosis-correction-2018",
      title: "The Effect of a Corrective Functional Exercise Program on Postural Thoracic Kyphosis in Teenagers: A Randomized Controlled Trial",
      authors: "Feng Q, Wang M, Zhang Y, Zhou Y",
      year: 2018,
      journal: "Clinical Rehabilitation",
      sourceType: "journal",
      description: "RCT showing corrective functional exercises reduce postural thoracic kyphosis in teenagers.",
      confidence: 0.8,
    },
    {
      slug: "csepregi-breathing-posture-2022",
      title: "Effects of Classical Breathing Exercises on Posture, Spinal and Chest Mobility Among Female University Students Compared to Currently Popular Training Programs",
      authors: "Csepregi É, Gyurcsik Z, Veres-Balajti I, et al.",
      year: 2022,
      journal: "International Journal of Environmental Research and Public Health",
      sourceType: "journal",
      description: "Breathing exercises improve chest expansion, spinal mobility (especially lateral flexion), and posture comparably to yoga and Pilates.",
      confidence: 0.8,
    },
    {
      slug: "eftekhari-breathing-kyphosis-2024",
      title: "Effects of Telerehabilitation-Based Respiratory and Corrective Exercises Among the Elderly With Thoracic Hyper-Kyphosis: A Clinical Trial",
      authors: "Eftekhari E, Sheikhhoseini R, Salahzadeh Z, Dadfar M",
      year: 2024,
      journal: "BMC Geriatrics",
      sourceType: "journal",
      description: "Telerehabilitation-based respiratory and corrective exercises improve thoracic kyphosis in elderly populations.",
      confidence: 0.8,
    },
    // Lumbar Spine and Core
    {
      slug: "calatayud-core-tolerability-2019",
      title: "Tolerability and Muscle Activity of Core Muscle Exercises in Chronic Low-Back Pain",
      authors: "Calatayud J, Escriche-Escuder A, Cruz-Montecinos C, et al.",
      year: 2019,
      journal: "International Journal of Environmental Research and Public Health",
      sourceType: "journal",
      description: "EMG study of core exercises in chronic LBP patients. Bird dog: 29% nEMG erector spinae. Curl-up: 48-50% nEMG rectus abdominis. All exercises well-tolerated.",
      confidence: 0.85,
    },
    {
      slug: "puntumetakul-core-adim-2021",
      title: "The Effects of Core Stabilization Exercise With the Abdominal Drawing-in Maneuver Technique Versus General Strengthening Exercise on Lumbar Segmental Motion in Patients With Clinical Lumbar Instability: A Randomized Controlled Trial With 12-Month Follow-Up",
      authors: "Puntumetakul R, Saiklang P, Tapanya W, et al.",
      year: 2021,
      journal: "International Journal of Environmental Research and Public Health",
      sourceType: "journal",
      description: "RCT with 12-month follow-up showing ADIM-based core stabilization reduces lumbar segmental translation more than general strengthening.",
      confidence: 0.85,
    },
    {
      slug: "guo-core-training-types-2025",
      title: "Effects of Different Types of Core Training on Pain and Functional Status in Patients With Chronic Nonspecific Low Back Pain: A Systematic Review and Meta-Analysis",
      authors: "Guo XB, Lan Q, Ding J, Tang L, Yang M",
      year: 2025,
      journal: "Frontiers in Physiology",
      sourceType: "journal",
      description: "Systematic review and meta-analysis comparing core training types for chronic nonspecific low back pain. Motor control exercises effective.",
      confidence: 0.85,
    },
    {
      slug: "kim-lumbar-stabilization-emg-2016",
      title: "Electromyographic Changes in Trunk Muscles During Graded Lumbar Stabilization Exercises",
      authors: "Kim CR, Park DK, Lee ST, Ryu JS",
      year: 2016,
      journal: "PM & R: The Journal of Injury, Function, and Rehabilitation",
      sourceType: "journal",
      description: "EMG analysis of trunk muscle activation during graded lumbar stabilization exercises including bird dog and dead bug progressions.",
      confidence: 0.8,
    },
    {
      slug: "fernandez-rodriguez-pilates-lbp-2022",
      title: "Best Exercise Options for Reducing Pain and Disability in Adults With Chronic Low Back Pain: Pilates, Strength, Core-Based, and Mind-Body. A Network Meta-Analysis",
      authors: "Fernández-Rodríguez R, Álvarez-Bueno C, Cavero-Redondo I, et al.",
      year: 2022,
      journal: "The Journal of Orthopaedic and Sports Physical Therapy",
      sourceType: "journal",
      description: "Network meta-analysis: Pilates has highest likelihood (93% for pain, 98% for disability) of reducing chronic low back pain.",
      confidence: 0.9,
    },
    // Shoulder Girdle
    {
      slug: "mendez-rebolledo-scapular-emg-2024",
      title: "Comparative Electromyographic Study of Scapular Stabilizing Muscles During Five Main Rehabilitation Exercises",
      authors: "Mendez-Rebolledo G, Araya-Quintanilla F, Guzmán-Muñoz E, et al.",
      year: 2024,
      journal: "American Journal of Physical Medicine & Rehabilitation",
      sourceType: "journal",
      description: "EMG study showing prone horizontal abduction with ER achieves optimal UT/MT (0.43) and UT/LT (0.30) activation ratios.",
      confidence: 0.85,
    },
    {
      slug: "andersen-scapular-intensity-2012",
      title: "Scapular Muscle Activity From Selected Strengthening Exercises Performed at Low and High Intensities",
      authors: "Andersen CH, Zebis MK, Saervoll C, et al.",
      year: 2012,
      journal: "Journal of Strength and Conditioning Research",
      sourceType: "journal",
      description: "Scapular muscle activation study at various intensities. Push-up plus activates serratus anterior highly with favorable LT/UT ratio.",
      confidence: 0.8,
    },
    {
      slug: "kibler-scapular-rehab-2008",
      title: "Electromyographic Analysis of Specific Exercises for Scapular Control in Early Phases of Shoulder Rehabilitation",
      authors: "Kibler WB, Sciascia AD, Uhl TL, Tambay N, Cunningham T",
      year: 2008,
      journal: "The American Journal of Sports Medicine",
      sourceType: "journal",
      description: "EMG analysis of exercises for early-phase scapular rehabilitation. Push-up plus addresses winging and promotes upward rotation.",
      confidence: 0.85,
    },
    {
      slug: "mulroy-shoulder-sci-2020",
      title: "A Primary Care Provider's Guide to Shoulder Pain After Spinal Cord Injury",
      authors: "Mulroy SJ, Hafdahl L, Dyson-Hudson T",
      year: 2020,
      journal: "Topics in Spinal Cord Injury Rehabilitation",
      sourceType: "guideline",
      description: "Clinical guideline on shoulder pain management. ER strengthening prevents superior humeral head migration and reduces impingement.",
      confidence: 0.85,
    },
    {
      slug: "escamilla-shoulder-rehab-2009",
      title: "Shoulder Muscle Activity and Function in Common Shoulder Rehabilitation Exercises",
      authors: "Escamilla RF, Yamashiro K, Paulos L, Andrews JR",
      year: 2009,
      journal: "Sports Medicine",
      sourceType: "journal",
      description: "Comprehensive review of shoulder muscle EMG during common rehabilitation exercises. Foundational reference for exercise selection.",
      confidence: 0.9,
    },
    // ── Shoulder Anatomy & Biomechanics Evidence (OpenEvidence verified) ──
    {
      slug: "axford-shoulder-moment-arms-2025",
      title: "Three-Dimensional Continuous Muscle Moment Arm Maps for the Anatomical Shoulder",
      authors: "Axford DT, Potra R, Appleyard R, et al.",
      year: 2025,
      journal: "Journal of Biomechanics",
      sourceType: "journal",
      description: "3D continuous moment arm maps for shoulder muscles. Reveals biphasic function of supraspinatus and plane-dependent roles of rotator cuff.",
      confidence: 0.9,
    },
    {
      slug: "bacle-infraspinatus-teres-2017",
      title: "Anatomy and Relations of the Infraspinatus and the Teres Minor Muscles: A Fresh Cadaver Dissection Study",
      authors: "Bacle G, Gregoire JM, Patat F, et al.",
      year: 2017,
      journal: "Surgical and Radiologic Anatomy",
      sourceType: "journal",
      description: "Fresh cadaver dissection study detailing anatomy and relations of infraspinatus and teres minor. Confirms origins, insertions, and nerve supply.",
      confidence: 0.9,
    },
    {
      slug: "sakoma-deltoid-segments-2011",
      title: "Anatomical and Functional Segments of the Deltoid Muscle",
      authors: "Sakoma Y, Sano H, Shinozaki N, et al.",
      year: 2011,
      journal: "Journal of Anatomy",
      sourceType: "journal",
      description: "Identifies seven anatomical segments of the deltoid based on intramuscular tendon distribution. Key reference for deltoid functional anatomy.",
      confidence: 0.85,
    },
    {
      slug: "hik-shoulder-moment-arms-2019",
      title: "The Moment Arms of the Muscles Spanning the Glenohumeral Joint: A Systematic Review",
      authors: "Hik F, Ackland DC",
      year: 2019,
      journal: "Journal of Anatomy",
      sourceType: "journal",
      description: "Systematic review of glenohumeral muscle moment arms. Clarifies primary/secondary roles for shoulder extension, adduction, and internal rotation.",
      confidence: 0.9,
    },
    {
      slug: "pearl-shoulder-emg-1992",
      title: "An Electromyographic Analysis of the Shoulder During Cones and Planes of Arm Motion",
      authors: "Pearl ML, Perry J, Torburn L, Gordon LH",
      year: 1992,
      journal: "Clinical Orthopaedics and Related Research",
      sourceType: "journal",
      description: "Classic EMG analysis of shoulder muscles across planes and cones of motion. Defines primary/secondary roles for flexion, abduction, and rotation.",
      confidence: 0.85,
    },
    {
      slug: "johnson-trapezius-anatomy-1994",
      title: "Anatomy and Actions of the Trapezius Muscle",
      authors: "Johnson G, Bogduk N, Nowitzke A, House D",
      year: 1994,
      journal: "Clinical Biomechanics",
      sourceType: "journal",
      description: "Detailed anatomy and biomechanical analysis of the three functional parts of the trapezius. Key reference for scapular movement roles.",
      confidence: 0.9,
    },
    {
      slug: "williams-scapulothoracic-1999",
      title: "Anatomy of the Scapulothoracic Articulation",
      authors: "Williams GR, Shakil M, Klimkiewicz J, Iannotti JP",
      year: 1999,
      journal: "Clinical Orthopaedics and Related Research",
      sourceType: "journal",
      description: "Comprehensive anatomy of the scapulothoracic articulation including muscle attachments, innervation, and blood supply of all scapular muscles.",
      confidence: 0.9,
    },
    {
      slug: "beheiry-pec-major-innervation-2012",
      title: "Innervation of the Pectoralis Major Muscle: Anatomical Study",
      authors: "Beheiry EE",
      year: 2012,
      journal: "Annals of Plastic Surgery",
      sourceType: "journal",
      description: "Anatomical study of pectoralis major innervation. Confirms clavicular head: lateral pectoral nerve (C5-C7); sternal head: medial and lateral pectoral nerves (C6-T1).",
      confidence: 0.85,
    },
    {
      slug: "reinold-rotator-cuff-emg-2004",
      title: "Electromyographic Analysis of the Rotator Cuff and Deltoid Musculature During Common Shoulder External Rotation Exercises",
      authors: "Reinold MM, Wilk KE, Fleisig GS, et al.",
      year: 2004,
      journal: "The Journal of Orthopaedic and Sports Physical Therapy",
      sourceType: "journal",
      description: "EMG analysis: side-lying ER achieves infraspinatus 62% MVIC, teres minor 67% MVIC. Key dosing reference for rotator cuff exercises.",
      confidence: 0.9,
    },
    {
      slug: "hawkes-glenohumeral-emg-2018",
      title: "Patterns of Muscle Coordination During Dynamic Glenohumeral Joint Elevation: An EMG Study",
      authors: "Hawkes DH, Khaiyat OA, Howard AJ, Kemp GJ, Frostick SP",
      year: 2018,
      journal: "PLoS One",
      sourceType: "journal",
      description: "EMG patterns during dynamic shoulder elevation. Confirms rotator cuff stabilizer roles during flexion and abduction.",
      confidence: 0.85,
    },
    {
      slug: "lafrance-rotator-cuff-fitt-2024",
      title: "The Efficacy of Exercise Therapy for Rotator Cuff-Related Shoulder Pain According to the FITT Principle: A Systematic Review With Meta-Analyses",
      authors: "Lafrance S, Charron M, Dubé MO, et al.",
      year: 2024,
      journal: "The Journal of Orthopaedic and Sports Physical Therapy",
      sourceType: "journal",
      description: "Motor control exercises show moderate-certainty evidence for superior outcomes vs nonspecific exercises. Disability reduction SMD: -0.29 (short) and -0.33 (medium term).",
      confidence: 0.9,
    },
    {
      slug: "hopewell-grasp-2021",
      title: "Progressive Exercise Compared With Best Practice Advice, With or Without Corticosteroid Injection, for the Treatment of Patients With Rotator Cuff Disorders (GRASP)",
      authors: "Hopewell S, Keene DJ, Marian IR, et al.",
      year: 2021,
      journal: "The Lancet",
      sourceType: "journal",
      description: "Multicentre RCT: progressive resistance training focusing on ER, flexion, and abduction is core component of evidence-based shoulder rehabilitation.",
      confidence: 0.95,
    },
    {
      slug: "berckmans-scapular-emg-2021",
      title: "Rehabilitation Exercises for Dysfunction of the Scapula: Exploration of Muscle Activity Using Fine-Wire EMG",
      authors: "Berckmans KR, Castelein B, Borms D, Parlevliet T, Cools A",
      year: 2021,
      journal: "The American Journal of Sports Medicine",
      sourceType: "journal",
      description: "Fine-wire EMG of scapular rehab exercises. Rhomboid major activation: lawnmower 59% MVIC, robbery 66% MVIC. Key reference for scapular exercise progression.",
      confidence: 0.9,
    },
    // ── Knee Anatomy & Biomechanics Evidence (OpenEvidence verified) ──────
    {
      slug: "waligora-quadriceps-anatomy-2009",
      title: "Clinical Anatomy of the Quadriceps Femoris and Extensor Apparatus of the Knee",
      authors: "Waligora AC, Johanson NA, Hirsch BE",
      year: 2009,
      journal: "Clinical Orthopaedics and Related Research",
      sourceType: "journal",
      description: "Comprehensive anatomy of quadriceps including rectus femoris dual head origin, vasti attachments, and extensor apparatus.",
      confidence: 0.9,
    },
    {
      slug: "grob-vm-vi-interaction-2018",
      title: "The Interaction Between the Vastus Medialis and Vastus Intermedius and Its Influence on the Extensor Apparatus of the Knee Joint",
      authors: "Grob K, Manestar M, Filgueira L, et al.",
      year: 2018,
      journal: "Knee Surgery, Sports Traumatology, Arthroscopy",
      sourceType: "journal",
      description: "VMO/VML subdivision, VM-VI interaction, and extensor apparatus. VMO fiber orientation 46-52° medially vs 15-18° for VML.",
      confidence: 0.9,
    },
    {
      slug: "olewnik-quadriceps-heads-2021",
      title: "Quadriceps or Multiceps Femoris? — Cadaveric Study",
      authors: "Olewnik Ł, Tubbs RS, Ruzik K, et al.",
      year: 2021,
      journal: "Clinical Anatomy",
      sourceType: "journal",
      description: "Cadaveric study showing additional quadriceps heads present in 64.1% of limbs. Challenges traditional four-head model.",
      confidence: 0.85,
    },
    {
      slug: "buford-knee-rotation-moment-arms-2001",
      title: "Internal/External Rotation Moment Arms of Muscles at the Knee",
      authors: "Buford WL, Ivey FM, Nakamura T, Patterson RM, Nguyen DK",
      year: 2001,
      journal: "The Knee",
      sourceType: "journal",
      description: "Rotational moment arms at 30° flexion: BF long head 18.5-31.5 mm, BF short head 14.7-27.9 mm, semimembranosus 10.1-11.6 mm, semitendinosus 6.8-9.0 mm.",
      confidence: 0.9,
    },
    {
      slug: "farfan-hamstring-innervation-2024",
      title: "Innervation Patterns of Hamstring Muscles, Including Morphological Descriptions and Clinical Implication",
      authors: "Farfán E, Rojas S, Olivé-Vilás R, Rodríguez-Baeza A",
      year: 2024,
      journal: "Surgical and Radiologic Anatomy",
      sourceType: "journal",
      description: "Hamstring innervation patterns: BF long head 1-2 tibial branches, BF short head single common fibular branch, semitendinosus always 2 branches.",
      confidence: 0.9,
    },
    {
      slug: "nyland-popliteus-2005",
      title: "Anatomy, Function, and Rehabilitation of the Popliteus Musculotendinous Complex",
      authors: "Nyland J, Lachman N, Kocabey Y, et al.",
      year: 2005,
      journal: "The Journal of Orthopaedic and Sports Physical Therapy",
      sourceType: "journal",
      description: "Popliteus anatomy, function (knee unlocking, IR, posterolateral stabilization), and rehabilitation considerations.",
      confidence: 0.9,
    },
    {
      slug: "jeon-popliteus-nerve-artery-2022",
      title: "Nerve and Arterial Supply Pattern of the Popliteus Muscle and Clinical Implications",
      authors: "Jeon A, Kim YG, Sohn Y, Lee JH",
      year: 2022,
      journal: "BioMed Research International",
      sourceType: "journal",
      description: "Popliteus innervation: 90% tibial nerve alone, 10% tibial+sciatic. Blood supply: inferior medial genicular artery (90%), posterior tibial artery (65%).",
      confidence: 0.85,
    },
    {
      slug: "flaxman-knee-muscle-roles-2017",
      title: "Predicting the Functional Roles of Knee Joint Muscles From Internal Joint Moments",
      authors: "Flaxman TE, Alkjær T, Simonsen EB, Krogsgaard MR, Benoit DL",
      year: 2017,
      journal: "Medicine and Science in Sports and Exercise",
      sourceType: "journal",
      description: "VL and VM act as general joint stabilizers with activation independent of moment direction. TFL secondary role in knee extension.",
      confidence: 0.9,
    },
    {
      slug: "flaxman-knee-synergies-2021",
      title: "Functional Muscle Synergies to Support the Knee Against Moment Specific Loads While Weight Bearing",
      authors: "Flaxman TE, Shourijeh MS, Smale KB, et al.",
      year: 2021,
      journal: "Journal of Electromyography and Kinesiology",
      sourceType: "journal",
      description: "Quadriceps co-activation particularly important for supporting knee against abduction and rotation loads. Medial hamstrings provide rotational stability.",
      confidence: 0.9,
    },
    {
      slug: "escamilla-squat-biomechanics-2001",
      title: "Knee Biomechanics of the Dynamic Squat Exercise",
      authors: "Escamilla RF",
      year: 2001,
      journal: "Medicine and Science in Sports and Exercise",
      sourceType: "journal",
      description: "Squat biomechanics: PF and TF forces increase with flexion. 0-50° minimal forces (early rehab). Parallel squat for healthy knees. Deep squats may increase meniscal/ligament injury potential.",
      confidence: 0.9,
    },
    {
      slug: "escamilla-cruciate-loading-2012",
      title: "Cruciate Ligament Loading During Common Knee Rehabilitation Exercises",
      authors: "Escamilla RF, Macleod TD, Wilk KE, Paulos L, Andrews JR",
      year: 2012,
      journal: "Proceedings of the Institution of Mechanical Engineers Part H",
      sourceType: "journal",
      description: "ACL loading: OKC higher than CKC. ACL loaded less at 50-100° knee angles. Forward trunk tilt reduces ACL loading. PCL loading hierarchy established.",
      confidence: 0.9,
    },
    {
      slug: "muyor-squat-lunge-emg-2020",
      title: "EMG Activity During Monopodal Squat, Forward Lunge and Lateral Step-Up",
      authors: "Muyor JM, Martín-Fuentes I, Rodríguez-Ridao D, Antequera-Vique JA",
      year: 2020,
      journal: "PLoS One",
      sourceType: "journal",
      description: "Monopodal squat: significantly higher EMG activity than lateral step-up and forward lunge in all muscles (d > 0.6). VL and VM highest activity.",
      confidence: 0.85,
    },
    {
      slug: "andersen-therapeutic-vs-heavy-2006",
      title: "Neuromuscular Activation in Conventional Therapeutic Exercises and Heavy Resistance Exercises: Implications for Rehabilitation",
      authors: "Andersen LL, Magnusson SP, Nielsen M, et al.",
      year: 2006,
      journal: "Physical Therapy",
      sourceType: "journal",
      description: "Quad activation 67-79% MVIC during squats. Heavy resistance (>60% MVIC) needed for hypertrophy. Conventional therapeutic exercises (<35% MVIC) insufficient.",
      confidence: 0.9,
    },
    {
      slug: "gryzlo-knee-rehab-emg-1994",
      title: "Electromyographic Analysis of Knee Rehabilitation Exercises",
      authors: "Gryzlo SM, Patek RM, Pink M, Perry J",
      year: 1994,
      journal: "The Journal of Orthopaedic and Sports Physical Therapy",
      sourceType: "journal",
      description: "VM and VL significantly more active during last 15° of extension. Hamstrings significantly less active than quadriceps during all squat phases.",
      confidence: 0.85,
    },
    {
      slug: "lawford-cochrane-knee-oa-2024",
      title: "Exercise for Osteoarthritis of the Knee",
      authors: "Lawford BJ, Hall M, Hinman RS, et al.",
      year: 2024,
      journal: "The Cochrane Database of Systematic Reviews",
      sourceType: "journal",
      description: "Cochrane review: exercise safe for knee OA with no increase in pain or disease progression. Benefits sustained 2-6 months after treatment ends.",
      confidence: 0.95,
    },
    {
      slug: "yan-knee-oa-exercise-modalities-2025",
      title: "Comparative Efficacy and Safety of Exercise Modalities in Knee Osteoarthritis: Systematic Review and Network Meta-Analysis",
      authors: "Yan L, Li D, Xing D, et al.",
      year: 2025,
      journal: "BMJ",
      sourceType: "journal",
      description: "Network meta-analysis: aerobic exercise highest probability of benefit for knee OA. 12-week programs show consistent mid-term benefits. Adverse events minor.",
      confidence: 0.95,
    },
    {
      slug: "zebis-acl-exercise-emg-2019",
      title: "EMG Evaluation of Bodyweight Exercise Progression in a Validated ACL Injury Rehabilitation Program",
      authors: "Zebis MK, Sørensen MH, Lauridsen HB, et al.",
      year: 2019,
      journal: "American Journal of Physical Medicine & Rehabilitation",
      sourceType: "journal",
      description: "Cook hip lift: highest hamstring activity (>60% MVIC ST and BF). Bodyweight exercises inadequately progress hamstring activity but successfully progress quads.",
      confidence: 0.85,
    },
    {
      slug: "hegyi-hamstring-hd-emg-2019",
      title: "High-Density Electromyography Activity in Various Hamstring Exercises",
      authors: "Hegyi A, Csala D, Péter A, Finni T, Cronin NJ",
      year: 2019,
      journal: "Scandinavian Journal of Medicine & Science in Sports",
      sourceType: "journal",
      description: "HD-EMG hamstring exercises: leg curls 40-54% MVIC (eccentric), 69-85% (concentric). Hip extension only BF-dominant exercise. Proximal-distal patterns exercise-dependent.",
      confidence: 0.9,
    },
    // ── Lumbar Spine Anatomy & Biomechanics Evidence (OpenEvidence verified) ──
    {
      slug: "harano-multifidus-reappraisal-2026",
      title: "An Insertion-Based Anatomical Reappraisal of the Lumbar Multifidus",
      authors: "Harano T, Tabira Y, Shimizu K, et al.",
      year: 2026,
      journal: "Clinical Anatomy",
      sourceType: "journal",
      description: "Reappraises lumbar multifidus anatomy: two distinct bundles — one from mammillary process/lateral sacral crest, another pennate bundle from thoracolumbar fascia.",
      confidence: 0.9,
    },
    {
      slug: "bogduk-lumbar-innervation-1983",
      title: "The Innervation of the Lumbar Spine",
      authors: "Bogduk N",
      year: 1983,
      journal: "Spine",
      sourceType: "journal",
      description: "Definitive mapping of lumbar spine innervation. Multifidus: medial branches; iliocostalis: lateral branches; longissimus: intermediate branches of dorsal rami.",
      confidence: 0.95,
    },
    {
      slug: "bogduk-erector-spinae-model-1992",
      title: "A Universal Model of the Lumbar Back Muscles in the Upright Position",
      authors: "Bogduk N, Macintosh JE, Pearcy MJ",
      year: 1992,
      journal: "Spine",
      sourceType: "journal",
      description: "Thoracic fibers of ES contribute 50% of total extensor moment at L4-L5; multifidus 20%. At upper lumbar levels, thoracic fibers contribute 70-86%.",
      confidence: 0.9,
    },
    {
      slug: "phillips-ql-biomechanics-2008",
      title: "Anatomy and Biomechanics of Quadratus Lumborum",
      authors: "Phillips S, Mercer S, Bogduk N",
      year: 2008,
      journal: "Proceedings of the Institution of Mechanical Engineers Part H",
      sourceType: "journal",
      description: "QL contributes <10% of extensor and lateral bending moments compared to ES and multifidus. Modest direct action on lumbar spine.",
      confidence: 0.9,
    },
    {
      slug: "urquhart-abdominal-morphology-2005",
      title: "Regional Morphology of the Transversus Abdominis and Obliquus Internus and Externus Abdominis Muscles",
      authors: "Urquhart DM, Barker PJ, Hodges PW, Story IH, Briggs CA",
      year: 2005,
      journal: "Clinical Biomechanics",
      sourceType: "journal",
      description: "TrA fascicle orientation: horizontal upper, increasing inferomedial lower. IO separable into two layers. TrA vertical TLF attachment averages 5.2 cm.",
      confidence: 0.9,
    },
    {
      slug: "hodges-iap-stiffness-2003",
      title: "Intervertebral Stiffness of the Spine Is Increased by Evoked Contraction of Transversus Abdominis and the Diaphragm",
      authors: "Hodges P, Kaigle Holm A, Holm S, et al.",
      year: 2003,
      journal: "Spine",
      sourceType: "journal",
      description: "In vivo porcine study: TrA and diaphragm contraction increases intervertebral stiffness and reduces relative displacement. Mechanistic basis for IAP stabilization.",
      confidence: 0.9,
    },
    {
      slug: "tayashiki-bracing-vs-hollowing-2016",
      title: "Intra-Abdominal Pressure and Trunk Muscular Activities During Abdominal Bracing and Hollowing",
      authors: "Tayashiki K, Takai Y, Maeo S, Kanehisa H",
      year: 2016,
      journal: "International Journal of Sports Medicine",
      sourceType: "journal",
      description: "Bracing generates IAP 116.4±15.0 mmHg vs hollowing 9.9±4.5 mmHg. IO highest activity during IAP generation tasks.",
      confidence: 0.85,
    },
    {
      slug: "bojairami-tlf-iap-stability-2022",
      title: "Coordination Between Trunk Muscles, Thoracolumbar Fascia, and Intra-Abdominal Pressure Toward Static Spine Stability",
      authors: "Bojairami IE, Driscoll M",
      year: 2022,
      journal: "Spine",
      sourceType: "journal",
      description: "TLF contributes 75% stability individually; synergistic activation of all tissues reaches 93%. IAP and muscle coordination provide mechanical contribution to stiffness control.",
      confidence: 0.85,
    },
    {
      slug: "cresswell-perturbation-iap-1994",
      title: "The Influence of Sudden Perturbations on Trunk Muscle Activity and Intra-Abdominal Pressure While Standing",
      authors: "Cresswell AG, Oddsson L, Thorstensson A",
      year: 1994,
      journal: "Experimental Brain Research",
      sourceType: "journal",
      description: "TrA is the first muscle active during unexpected ventral loading. Foundational evidence for anticipatory postural adjustments.",
      confidence: 0.9,
    },
    {
      slug: "garcia-jaen-plank-hollowing-2020",
      title: "Influence of Abdominal Hollowing Maneuver on the Core Musculature Activation During the Prone Plank Exercise",
      authors: "García-Jaén M, Cortell-Tormo JM, Hernández-Sánchez S, Tortosa-Martínez J",
      year: 2020,
      journal: "International Journal of Environmental Research and Public Health",
      sourceType: "journal",
      description: "Plank with hollowing: total intensity significantly greater (p<0.001, ES=3.01). IO (ES=2.0-2.3), EO (ES=1.0-1.4), lumbar ES (ES=0.6) all increased.",
      confidence: 0.85,
    },
    {
      slug: "mcgill-lumbar-kinetics-1991",
      title: "Kinetic Potential of the Lumbar Trunk Musculature About Three Orthogonal Orthopaedic Axes in Extreme Postures",
      authors: "McGill SM",
      year: 1991,
      journal: "Spine",
      sourceType: "journal",
      description: "Large obliques dominate over small spinal rotators. Portions of ES have appreciable torque potential about all three orthopedic axes.",
      confidence: 0.9,
    },
    {
      slug: "anders-trunk-force-directions-2018",
      title: "Main Force Directions of Trunk Muscles: A Pilot Study in Healthy Male Subjects",
      authors: "Anders C, Steiniger B",
      year: 2018,
      journal: "Human Movement Science",
      sourceType: "journal",
      description: "Force direction angles: RA ±14°, EO ±32°, IO ±47°, iliocostalis ~±90° from sagittal plane.",
      confidence: 0.85,
    },
    {
      slug: "mueller-stabilization-dose-response-2020",
      title: "Dose-Response-Relationship of Stabilisation Exercises in Patients With Chronic Non-Specific Low Back Pain",
      authors: "Mueller J, Niederer D",
      year: 2020,
      journal: "Scientific Reports",
      sourceType: "journal",
      description: "20-30 min training duration elicits largest effect (moderate quality). 3-5x/week largest effect (low quality). Effect sizes: d=1.80 pain, d=1.70 disability.",
      confidence: 0.9,
    },
    {
      slug: "sedlmayr-hip-flexor-revision-2022",
      title: "Revision of Hip Flexor Anatomy and Function in Modern Humans, and Implications for the Evolution of Hominin Bipedalism",
      authors: "Sedlmayr JC, Bates KT, Wisco JJ, Schachner ER",
      year: 2022,
      journal: "Anatomical Record",
      sourceType: "journal",
      description: "Psoas tendon inserts separately from iliacus into crest on lesser trochanter. Iliacus inserts fleshly. Challenges traditional 'iliopsoas' model.",
      confidence: 0.85,
    },
    {
      slug: "skyrme-psoas-rotation-1999",
      title: "Psoas Major and Its Controversial Rotational Action",
      authors: "Skyrme AD, Cahill DJ, Marsh HP, Ellis H",
      year: 1999,
      journal: "Clinical Anatomy",
      sourceType: "journal",
      description: "In anatomical position, psoas produces hip flexion without rotational component. With hip abducted, produces flexion, adduction, and lateral rotation.",
      confidence: 0.85,
    },
    // ── Hip Anatomy & Biomechanics Evidence (OpenEvidence verified) ───────
    {
      slug: "anetai-glut-max-structure-2025",
      title: "Structural Re-Evaluation of the Human Gluteus Maximus",
      authors: "Anetai H, Kato K, Kudoh H, Sakai T, Ichimura K",
      year: 2025,
      journal: "Scientific Reports",
      sourceType: "journal",
      description: "Major re-evaluation: superior 3/4 inserts primarily into gluteal tuberosity via plate-like tendon, not primarily IT tract. Inferior portion terminates at lateral femoral intermuscular septum.",
      confidence: 0.9,
    },
    {
      slug: "neumann-hip-kinesiology-2010",
      title: "Kinesiology of the Hip: A Focus on Muscular Actions",
      authors: "Neumann DA",
      year: 2010,
      journal: "The Journal of Orthopaedic and Sports Physical Therapy",
      sourceType: "journal",
      description: "Comprehensive hip muscle kinesiology. Definitive reference for muscle roles in flexion, extension, abduction, adduction, and rotation.",
      confidence: 0.95,
    },
    {
      slug: "flack-hip-abductor-anatomy-2014",
      title: "The Anatomy of the Hip Abductor Muscles",
      authors: "Flack NA, Nicholson HD, Woodley SJ",
      year: 2014,
      journal: "Clinical Anatomy",
      sourceType: "journal",
      description: "Gluteus medius and minimus: four anatomical compartments each with differential function. Three origin sites for glut med. Distinct innervation branches per region.",
      confidence: 0.9,
    },
    {
      slug: "yoo-short-lateral-rotators-2015",
      title: "An Appraisal of the Short Lateral Rotators of the Hip Joint",
      authors: "Yoo S, Dedova I, Pather N",
      year: 2015,
      journal: "Clinical Anatomy",
      sourceType: "journal",
      description: "Comprehensive appraisal of piriformis, obturator internus/externus, gemelli, and quadratus femoris. Origins, insertions, innervation, and functional roles.",
      confidence: 0.9,
    },
    {
      slug: "takizawa-adductor-magnus-innervation-2014",
      title: "The Adductor Part of the Adductor Magnus Is Innervated by Both Obturator and Sciatic Nerves",
      authors: "Takizawa M, Suzuki D, Ito H, Fujimiya M, Uchiyama E",
      year: 2014,
      journal: "Clinical Anatomy",
      sourceType: "journal",
      description: "Adductor portion of adductor magnus receives dual innervation (obturator + sciatic) in >90% of cases. Challenges traditional single-nerve model.",
      confidence: 0.9,
    },
    {
      slug: "collings-gluteal-forces-2023",
      title: "Gluteal Muscle Forces During Hip-Focused Injury Prevention and Rehabilitation Exercises",
      authors: "Collings TJ, Bourne MN, Barrett RS, et al.",
      year: 2023,
      journal: "Medicine and Science in Sports and Exercise",
      sourceType: "journal",
      description: "Gluteal force data: single-leg RDL — glut max 500-655 N, glut med 283-405 N, glut min 267-389 N. 12RM load increases peak forces by 28-150 N.",
      confidence: 0.9,
    },
    {
      slug: "giphart-pectineus-piriformis-emg-2012",
      title: "Recruitment and Activity of the Pectineus and Piriformis Muscles During Hip Rehabilitation Exercises",
      authors: "Giphart JE, Stull JD, Laprade RF, Wahoff MS, Philippon MJ",
      year: 2012,
      journal: "The American Journal of Sports Medicine",
      sourceType: "journal",
      description: "Piriformis: highest activation during prone heel squeeze (24.3% MVC) and single-leg hip thrust (35.7% MVC). Pectineus functions as hip stabilizer during rotation.",
      confidence: 0.9,
    },
    {
      slug: "kim-deep-gluteal-mri-2025",
      title: "Superficial and Deep Gluteal Muscle Activation During Common Therapeutic Exercises: A Muscle Functional MRI Analysis",
      authors: "Kim S, Burland JP, Morgan KD, et al.",
      year: 2025,
      journal: "Sports Health",
      sourceType: "journal",
      description: "fMRI: ABD-ER most effective for all gluteals — TFL 17.8%, glut min 18.1%, piriformis 23.8%, gemelli 18.7-21.4%. Higher activation than clamshell or reverse clamshell.",
      confidence: 0.85,
    },
    {
      slug: "philippon-glut-med-rehab-2011",
      title: "Rehabilitation Exercise Progression for the Gluteus Medius Muscle With Consideration for Iliopsoas Tendinitis",
      authors: "Philippon MJ, Decker MJ, Giphart JE, et al.",
      year: 2011,
      journal: "The American Journal of Sports Medicine",
      sourceType: "journal",
      description: "Phase-based gluteus medius rehab progression. Phase I: bridges/step-ups. Phase II: clamshells/wall-sliding. Phase III: single-leg exercises/prone heel squeeze.",
      confidence: 0.9,
    },
    {
      slug: "brosseau-ottawa-panel-hip-oa-2016",
      title: "Ottawa Panel Evidence-Based Clinical Practice Guidelines for Therapeutic Exercise in the Management of Hip Osteoarthritis",
      authors: "Brosseau L, Wells GA, Pugh AG, et al.",
      year: 2016,
      journal: "Clinical Rehabilitation",
      sourceType: "guideline",
      description: "Grade A evidence: 8-24 weeks progressive strength training, 2-3 sessions/week. ≥15% improvement threshold for clinically meaningful outcomes.",
      confidence: 0.9,
    },
    {
      slug: "rostron-gluteal-hypertrophy-2022",
      title: "Effects of a Targeted Resistance Intervention on Gluteal Muscle Hypertrophy in People With Hip Osteoarthritis",
      authors: "Rostron ZPJ, Zacharias A, Semciw AI, et al.",
      year: 2022,
      journal: "BMC Musculoskeletal Disorders",
      sourceType: "journal",
      description: "12-week targeted resistance produces gluteus minimus hypertrophy (0.06 cm³/kg, p=0.025) in hip OA patients. First evidence of gluteal hypertrophy from targeted exercise in OA.",
      confidence: 0.85,
    },
    // ── Cervical Spine Anatomy & Biomechanics Evidence (OpenEvidence verified) ──
    {
      slug: "kennedy-dcf-fascicular-anatomy-2017",
      title: "Do Longus Capitis and Colli Really Stabilise the Cervical Spine? A Study of Their Fascicular Anatomy and Peak Force Capabilities",
      authors: "Kennedy E, Albert M, Nicholson H",
      year: 2017,
      journal: "Musculoskeletal Science & Practice",
      sourceType: "journal",
      description: "Longus colli has complex three-part fascicular anatomy (superior oblique, vertical, inferior oblique). Spans multiple segments.",
      confidence: 0.9,
    },
    {
      slug: "cagnie-dcf-mri-2010",
      title: "A Magnetic Resonance Imaging Investigation Into the Function of the Deep Cervical Flexors During Craniocervical Flexion",
      authors: "Cagnie B, D'Hooge R, Achten E, Cambier D, Danneels L",
      year: 2010,
      journal: "Journal of Manipulative and Physiological Therapeutics",
      sourceType: "journal",
      description: "Longus capitis: 11.1% CSA increase at C0-C1 during CCF. Longus colli: 17.4% CSA increase at C2-C3. Differential activation patterns confirmed.",
      confidence: 0.9,
    },
    {
      slug: "falla-dcf-emg-2003",
      title: "An Electromyographic Analysis of the Deep Cervical Flexor Muscles in Performance of Craniocervical Flexion",
      authors: "Falla D, Jull G, Dall'Alba P, Rainoldi A, Merletti R",
      year: 2003,
      journal: "Physical Therapy",
      sourceType: "journal",
      description: "Linear relationship between pressure levels (22-30 mmHg) and deep cervical flexor EMG amplitude. Foundational CCF biofeedback reference.",
      confidence: 0.95,
    },
    {
      slug: "falla-dcf-pain-correlation-2012",
      title: "The Change in Deep Cervical Flexor Activity After Training Is Associated With the Degree of Pain Reduction",
      authors: "Falla D, O'Leary S, Farina D, Jull G",
      year: 2012,
      journal: "The Clinical Journal of Pain",
      sourceType: "journal",
      description: "DCF training increases activation and correlates with pain reduction. 10 reps × 10 sec holds at progressive pressure targets. 6-week minimum program.",
      confidence: 0.9,
    },
    {
      slug: "karahan-suboccipital-morphometry-2025",
      title: "Morphometric Characteristics and Variations of the Suboccipital Muscles: A Cadaveric Study",
      authors: "Karahan M, Bozer C, Çıkmaz S, Seyaz M, Pehli̇van M",
      year: 2025,
      journal: "Musculoskeletal Science & Practice",
      sourceType: "journal",
      description: "Cadaveric morphometry of all four suboccipital muscles. Confirms individual origins, insertions, and variations.",
      confidence: 0.85,
    },
    {
      slug: "nolan-cervical-extensors-1988",
      title: "Biomechanical Evaluation of the Extensor Musculature of the Cervical Spine",
      authors: "Nolan JP, Sherk HH",
      year: 1988,
      journal: "Spine",
      sourceType: "journal",
      description: "Semispinalis capitis and cervicis: primary cervical extensors with greatest force-generating capacity.",
      confidence: 0.9,
    },
    {
      slug: "kwon-splenius-innervation-2020",
      title: "Intramuscular Innervation Patterns of the Splenius Capitis and Splenius Cervicis",
      authors: "Kwon HJ, Yang HM, Won SY",
      year: 2020,
      journal: "Clinical Anatomy",
      sourceType: "journal",
      description: "Splenius capitis innervation: dorsal rami C3-C5. Splenius cervicis: dorsal rami C5-C7. Clinical implications for botulinum toxin injections.",
      confidence: 0.85,
    },
    {
      slug: "olinger-scalene-rotation-2010",
      title: "Functional Anatomy of Human Scalene Musculature: Rotation of the Cervical Spine",
      authors: "Olinger AB, Homier P",
      year: 2010,
      journal: "Journal of Manipulative and Physiological Therapeutics",
      sourceType: "journal",
      description: "Scalenes produce ipsilateral rotation in addition to flexion and lateral flexion. Individual muscle-specific origins confirmed.",
      confidence: 0.85,
    },
    {
      slug: "tang-cervical-kinematics-2021",
      title: "In Vivo 3-Dimensional Kinematics Study of the Healthy Cervical Spine",
      authors: "Tang B, Yao H, Wang S, et al.",
      year: 2021,
      journal: "Spine",
      sourceType: "journal",
      description: "C1-C2 accounts for ~70% of total cervical rotation (obliquus capitis inferior). In vivo 3D kinematics with CBCT.",
      confidence: 0.9,
    },
    {
      slug: "dezoete-neck-exercise-nma-2020",
      title: "Comparative Effectiveness of Physical Exercise Interventions for Chronic Non-Specific Neck Pain: Network Meta-Analysis",
      authors: "de Zoete RM, Armfield NR, McAuley JH, Chen K, Sterling M",
      year: 2020,
      journal: "British Journal of Sports Medicine",
      sourceType: "journal",
      description: "Network meta-analysis of 40 RCTs. Mindfulness-based exercises (yoga/Pilates/tai chi/qigong) show superior pain reduction (SMD -0.84).",
      confidence: 0.95,
    },
    {
      slug: "price-neck-exercise-delphi-2021",
      title: "Expert Consensus on Important Chronic Non-Specific Neck Pain Motor Control and Segmental Exercise and Dosage Variables",
      authors: "Price J, Rushton A, Tyros V, Heneghan NR",
      year: 2021,
      journal: "PLoS One",
      sourceType: "journal",
      description: "International Delphi study: intensity of effort, frequency, and repetitions most important dosing variables (88-96% agreement).",
      confidence: 0.85,
    },
    {
      slug: "prodoehl-longus-colli-force-direction-2025",
      title: "Promoting Longus Colli Muscle Activation: Force Direction in Sitting Matters",
      authors: "Prodoehl J, Pathak R, Glavanovits J, et al.",
      year: 2025,
      journal: "Musculoskeletal Science & Practice",
      sourceType: "journal",
      description: "Ipsilateral oblique force direction in sitting enhances longus colli activation. Progression for CCF training beyond supine.",
      confidence: 0.85,
    },
    {
      slug: "sremakaew-sensorimotor-rehab-2023",
      title: "Effectiveness of Adding Rehabilitation of Cervical Related Sensorimotor Control to Manual Therapy and Exercise for Neck Pain",
      authors: "Sremakaew M, Jull G, Treleaven J, Uthaikhup S",
      year: 2023,
      journal: "Musculoskeletal Science & Practice",
      sourceType: "journal",
      description: "Adding JPS/oculomotor + balance exercises to manual therapy: medium to large effect sizes for proprioception, balance, and long-term pain reduction.",
      confidence: 0.85,
    },
    // Hip and Pelvis
    {
      slug: "va-hip-knee-oa-2020",
      title: "The Non-Surgical Management of Hip & Knee Osteoarthritis (OA) (2020)",
      authors: "Matthew Bair MD MS, John Cody MD, Jess Edison MD, et al.",
      year: 2020,
      sourceType: "guideline",
      description: "VA clinical practice guideline for non-surgical management of hip and knee OA. Supports hip abductor/extensor and quadriceps strengthening.",
      confidence: 0.9,
    },
    {
      slug: "cibulka-hip-oa-cpg-2017",
      title: "Hip Pain and Mobility Deficits-Hip Osteoarthritis: Revision 2017",
      authors: "Cibulka MT, Bloom NJ, Enseki KR, et al.",
      year: 2017,
      journal: "The Journal of Orthopaedic and Sports Physical Therapy",
      sourceType: "guideline",
      description: "Clinical practice guideline for hip OA. Flexibility exercises and hip ROM improvement essential for function.",
      confidence: 0.9,
    },
    {
      slug: "moreside-hip-rom-2012",
      title: "Hip Joint Range of Motion Improvements Using Three Different Interventions",
      authors: "Moreside JM, McGill SM",
      year: 2012,
      journal: "Journal of Strength and Conditioning Research",
      sourceType: "journal",
      description: "Three interventions for hip ROM improvement. Limited hip mobility affects lumbar spine mechanics.",
      confidence: 0.8,
    },
    {
      slug: "hayashi-pstr-hip-2022",
      title: "Effects of Pericapsular Soft Tissue and Realignment Exercises for Patients With Osteoarthritis of the Hip and Harris Hip Score Below 60 Points",
      authors: "Hayashi K, Tsunoda T, Tobo Y, Ichikawa F, Shimose T",
      year: 2022,
      journal: "Current Medical Research and Opinion",
      sourceType: "journal",
      description: "PSTR exercises including pelvic tilts significantly improve pain (NRS) and function (Harris Hip Score) even in severe hip OA.",
      confidence: 0.8,
    },
    // Knee
    {
      slug: "sharma-knee-oa-2021",
      title: "Osteoarthritis of the Knee",
      authors: "Sharma L",
      year: 2021,
      journal: "The New England Journal of Medicine",
      sourceType: "journal",
      description: "Comprehensive NEJM review of knee OA. Quadriceps strengthening fundamental for management.",
      confidence: 0.95,
    },
    {
      slug: "zeng-exercise-knee-oa-2022",
      title: "Benefits and Mechanisms of Exercise Training for Knee Osteoarthritis",
      authors: "Zeng CY, Zhang ZR, Tang ZM, Hua FZ",
      year: 2022,
      journal: "Frontiers in Physiology",
      sourceType: "journal",
      description: "Review of benefits and mechanisms of exercise for knee OA. Supports combined quad and posterior chain strengthening.",
      confidence: 0.85,
    },
    {
      slug: "roos-neuromuscular-2025",
      title: "An Exercise Therapists' Guide to Neuromuscular Exercise for People With Knee or Hip Osteoarthritis",
      authors: "Roos EM, Kroman S, Ageberg E",
      year: 2025,
      journal: "The Journal of Orthopaedic and Sports Physical Therapy",
      sourceType: "journal",
      description: "Practical guide for neuromuscular exercise in knee/hip OA. Addresses proprioceptive deficits and ADL function.",
      confidence: 0.85,
    },
    // Ankle and Foot
    {
      slug: "wu-ankle-sprain-2025",
      title: "Management of Acute Ankle Sprains: Common Questions and Answers",
      authors: "Wu V, Padilla CA, Smith NA",
      year: 2025,
      journal: "American Family Physician",
      sourceType: "journal",
      description: "Clinical guidance on ankle sprain management including resisted exercises for restoring ROM and strength.",
      confidence: 0.85,
    },
    {
      slug: "aafp-ankle-recovery-2025",
      title: "Recovering From an Ankle Sprain",
      authors: "American Academy of Family Physicians",
      year: 2025,
      sourceType: "guideline",
      description: "AAFP patient guideline for ankle sprain recovery. Supports resisted dorsiflexion/plantarflexion and eversion/inversion strengthening.",
      confidence: 0.8,
    },
    {
      slug: "zhang-ankle-instability-2025",
      title: "Effectiveness of Exercise Therapy on Chronic Ankle Instability: A Meta-Analysis",
      authors: "Zhang C, Luo Z, Wu D, et al.",
      year: 2025,
      journal: "Scientific Reports",
      sourceType: "journal",
      description: "Meta-analysis showing long-term multifaceted exercise including proprioceptive training has superior efficacy for chronic ankle instability.",
      confidence: 0.85,
    },
    // Integration / Low Back Pain
    {
      slug: "liu-lbp-exercise-2025",
      title: "Effects of Different Exercise Interventions on Lower Back Pain: A Systematic Review and Meta-Analysis",
      authors: "Liu X, Gao W, Wu P, et al.",
      year: 2025,
      journal: "Frontiers in Physiology",
      sourceType: "journal",
      description: "Systematic review of exercise interventions for lower back pain. Supports pelvic tilts and multimodal approaches.",
      confidence: 0.85,
    },
    // ── Ankle Evidence (OpenEvidence verified) ────────────────────────────
    {
      slug: "mullaney-triceps-surae-emg-2011",
      title: "EMG Analysis of the Triceps Surae Muscle Complex During Achilles Tendon Rehabilitation Program Exercises",
      authors: "Mullaney M, Tyler TF, McHugh M, et al.",
      year: 2011,
      journal: "Sports Health",
      sourceType: "journal",
      description: "EMG: seated toe raises 11% MVIC, prone pumps 38%, resistance band PF 45%, single-leg heel raise 112%, single-leg jump 129% MVIC.",
      confidence: 0.9,
    },
    {
      slug: "borreani-unstable-ankle-emg-2013",
      title: "Exercise Intensity Progression for Exercises on Unstable and Stable Platforms Based on Ankle Muscle Activation",
      authors: "Borreani S, Calatayud J, Martin J, et al.",
      year: 2013,
      journal: "Gait & Posture",
      sourceType: "journal",
      description: "Unipedal stance on soft surface with resistance: highest EMG for tibialis anterior, peroneus longus, and soleus. Peroneus longus 25% MVIC on wobble board.",
      confidence: 0.85,
    },
    {
      slug: "wagemans-ankle-reinjury-2022",
      title: "Exercise-Based Rehabilitation Reduces Reinjury Following Acute Lateral Ankle Sprain",
      authors: "Wagemans J, Bleakley C, Taeymans J, et al.",
      year: 2022,
      journal: "PLoS One",
      sourceType: "journal",
      description: "Exercise therapy reduces re-injury prevalence at 12 months vs usual care. Bracing reduces recurrent sprain by 60% (OR: 0.60).",
      confidence: 0.9,
    },
    // ── Elbow Evidence (OpenEvidence verified) ────────────────────────────
    {
      slug: "buchanan-elbow-strategies-1989",
      title: "Strategies for Muscle Activation During Isometric Torque Generation at the Human Elbow",
      authors: "Buchanan TS, Rovai GP, Rymer WZ",
      year: 1989,
      journal: "Journal of Neurophysiology",
      sourceType: "journal",
      description: "Three flexors show situation-dependent activation. Brachialis and brachioradialis: consistent positive linear relationship. Biceps often most active when others are least active.",
      confidence: 0.9,
    },
    {
      slug: "marcolin-curl-variants-emg-2018",
      title: "Differences in EMG of Biceps Brachii and Brachioradialis While Performing Three Variants of Curl",
      authors: "Marcolin G, Panizzolo FA, Petrone N, et al.",
      year: 2018,
      journal: "PeerJ",
      sourceType: "journal",
      description: "EZ-bar curl: higher activation of both biceps and brachioradialis throughout ROM. Barbell: higher brachioradialis concentric. Dumbbell: lowest overall.",
      confidence: 0.85,
    },
    {
      slug: "karanasios-lateral-elbow-2021",
      title: "Exercise Interventions in Lateral Elbow Tendinopathy Have Better Outcomes Than Passive Interventions",
      authors: "Karanasios S, Korakakis V, Whiteley R, et al.",
      year: 2021,
      journal: "British Journal of Sports Medicine",
      sourceType: "journal",
      description: "Systematic review: exercise better than passive interventions for lateral elbow tendinopathy. Effects are small but significant (VAS SMD -0.63, strength SMD 1.05).",
      confidence: 0.9,
    },
    // ── Wrist Evidence (OpenEvidence verified) ────────────────────────────
    {
      slug: "forman-wrist-flexion-extension-emg-2020",
      title: "Characterizing Forearm Muscle Activity During Dynamic Wrist Flexion-Extension Movement",
      authors: "Forman DA, Forman GN, Avila-Mireles EJ, et al.",
      year: 2020,
      journal: "Journal of Biomechanics",
      sourceType: "journal",
      description: "Wrist extensors show high co-contraction ratios (2.28 ± 2.04) during flexion. Vulnerability to overuse during dynamic tasks.",
      confidence: 0.85,
    },
    {
      slug: "shimose-wrist-extension-grip-2011",
      title: "Effect of Submaximal Isometric Wrist Extension Training on Grip Strength",
      authors: "Shimose R, Matsunaga A, Muro M",
      year: 2011,
      journal: "European Journal of Applied Physiology",
      sourceType: "journal",
      description: "30 reps at 70% MVC, 5 days/week for 8 weeks significantly increases grip strength by improving extensor activation balance.",
      confidence: 0.85,
    },
    // ── Hand Evidence (OpenEvidence verified) ─────────────────────────────
    {
      slug: "akbas-grip-strength-meta-2025",
      title: "Hand-Focused Strength and Proprioceptive Training for Improving Grip Strength and Manual Dexterity: A Systematic Review and Meta-Analysis",
      authors: "Akbaş A",
      year: 2025,
      journal: "Journal of Clinical Medicine",
      sourceType: "journal",
      description: "Large effect on grip strength (Hedges' g = 0.44, CI 0.23-0.64). Greater effects in older adults (g = 0.97). 2-3x/week optimal.",
      confidence: 0.9,
    },
    {
      slug: "brosseau-hand-oa-guidelines-2018",
      title: "The Ottawa Panel Guidelines on Programmes Involving Therapeutic Exercise for the Management of Hand Osteoarthritis",
      authors: "Brosseau L, Thevenot O, MacKiddie O, et al.",
      year: 2018,
      journal: "Clinical Rehabilitation",
      sourceType: "guideline",
      description: "46 positive-grade recommendations for combined ROM + isotonic + isometric + functional exercise programs for hand OA.",
      confidence: 0.9,
    },
    // ── Thoracic Spine Evidence (OpenEvidence verified) ───────────────────
    {
      slug: "de-ridder-trunk-extension-emg-2013",
      title: "Posterior Muscle Chain Activity During Various Extension Exercises: An Observational Study",
      authors: "De Ridder EM, Van Oosterwijck JO, Vleeming A, Vanderstraeten GG, Danneels LA",
      year: 2013,
      journal: "BMC Musculoskeletal Disorders",
      sourceType: "journal",
      description: "Longissimus/iliocostalis thoracis: 64.9 ± 27.1% MVC during prone extension. Dynamic-static performance increases lumbar but not thoracic activity.",
      confidence: 0.9,
    },
    {
      slug: "lee-thoracic-multifidus-rotation-2005",
      title: "Differential Activation of the Thoracic Multifidus and Longissimus Thoracis During Trunk Rotation",
      authors: "Lee LJ, Coppieters MW, Hodges PW",
      year: 2005,
      journal: "Spine",
      sourceType: "journal",
      description: "Longissimus increases with ipsilateral rotation at T5, decreases with contralateral. Multifidus controls coupling between rotation and lateral flexion T8-T11.",
      confidence: 0.9,
    },
    {
      slug: "cornwall-transversospinal-morphology-2011",
      title: "Functional Morphology of the Thoracolumbar Transversospinal Muscles",
      authors: "Cornwall J, Stringer MD, Duxson M",
      year: 2011,
      journal: "Spine",
      sourceType: "journal",
      description: "Multifidus/rotatores: 89% Type I fibers, multipennate. No discrete cleavage planes between them. Fine-tuning role for segmental stabilization.",
      confidence: 0.9,
    },
    {
      slug: "de-troyer-intercostal-action-2005",
      title: "Respiratory Action of the Intercostal Muscles",
      authors: "De Troyer A, Kirkwood PA, Wilson TA",
      year: 2005,
      journal: "Physiological Reviews",
      sourceType: "journal",
      description: "External intercostals: inspiratory advantage greatest in dorsal rostral interspaces. Internal intercostals: expiratory advantage greatest caudally. Parasternal portions inspiratory.",
      confidence: 0.95,
    },
  ];

  for (const s of sources) {
    await prisma.researchSource.upsert({
      where: { slug: s.slug },
      update: {
        title: s.title,
        authors: s.authors,
        year: s.year,
        sourceType: s.sourceType,
        description: s.description,
        confidence: s.confidence,
      },
      create: {
        slug: s.slug,
        title: s.title,
        authors: s.authors,
        year: s.year,
        sourceType: s.sourceType,
        description: s.description,
        status: "reviewed",
        confidence: s.confidence,
      },
    });
  }

  logCount("sources", sources.length);

  // Wire sources broadly to entities
  logSection("Source–Entity links");
  const neumannSource = await prisma.researchSource.findUnique({ where: { slug: "neumann-kinesiology-2017" } });
  const kendallSource = await prisma.researchSource.findUnique({ where: { slug: "kendall-muscles-2005" } });
  const kisnerSource = await prisma.researchSource.findUnique({ where: { slug: "kisner-therapeutic-2017" } });
  const mageeSource = await prisma.researchSource.findUnique({ where: { slug: "magee-orthopedic-2014" } });
  const acsmSource = await prisma.researchSource.findUnique({ where: { slug: "acsm-guidelines-2021" } });

  async function linkSource(sourceId: string, entityType: string, entityId: string, field: string, notes: string) {
    const existing = await prisma.sourceOnEntity.findFirst({
      where: { sourceId, [field]: entityId },
    });
    if (!existing) {
      await prisma.sourceOnEntity.create({
        data: { entityType, [field]: entityId, sourceId, notes },
      });
    }
  }

  let count = 0;

  if (neumannSource) {
    // Neumann covers all muscles, movements, and regions
    const allMuscles = await prisma.muscle.findMany();
    for (const m of allMuscles) { await linkSource(neumannSource.id, "Muscle", m.id, "muscleId", "Anatomy reference"); count++; }
    const allMovements = await prisma.movement.findMany();
    for (const m of allMovements) { await linkSource(neumannSource.id, "Movement", m.id, "movementId", "Biomechanics reference"); count++; }
    const allRegions = await prisma.region.findMany();
    for (const r of allRegions) { await linkSource(neumannSource.id, "Region", r.id, "regionId", "Regional anatomy reference"); count++; }
  }

  if (kendallSource) {
    // Kendall covers all muscles (testing reference)
    const allMuscles = await prisma.muscle.findMany();
    for (const m of allMuscles) { await linkSource(kendallSource.id, "Muscle", m.id, "muscleId", "Muscle testing reference"); count++; }
  }

  if (kisnerSource) {
    // Kisner covers all exercises
    const allExercises = await prisma.exercise.findMany();
    for (const e of allExercises) { await linkSource(kisnerSource.id, "Exercise", e.id, "exerciseId", "Exercise technique reference"); count++; }
  }

  if (mageeSource) {
    // Magee covers all joints
    const allJoints = await prisma.joint.findMany();
    for (const j of allJoints) { await linkSource(mageeSource.id, "Joint", j.id, "jointId", "Joint assessment reference"); count++; }
  }

  if (acsmSource) {
    // ACSM covers all exercises (prescription guidelines)
    const allExercises = await prisma.exercise.findMany();
    for (const e of allExercises) { await linkSource(acsmSource.id, "Exercise", e.id, "exerciseId", "Exercise prescription guidelines"); count++; }
  }

  logCount("source–entity links", count);

  // ── Targeted Evidence Links: Research Sources → Specific Exercises ──────
  logSection("Targeted evidence links");

  const exerciseSourceMap: Record<string, string[]> = {
    // Cervical Spine
    "deep-neck-flexor-training": [
      "sun-cervicothoracic-2024", "gross-neck-exercises-2015",
      "amiri-arimi-deep-flexors-2017", "moon-cervical-muscle-2021",
    ],
    "scapular-stability-rows": [
      "sun-cervicothoracic-2024", "gross-neck-exercises-2015",
      "mueller-neck-dose-response-2023", "cho-thoracic-vs-cervical-2017",
    ],
    "cervicothoracic-self-mobilization": [
      "sun-cervicothoracic-2024", "cho-thoracic-vs-cervical-2017",
    ],
    // Thoracic Spine
    "thoracic-extension-rotation-mobilization": [
      "cho-thoracic-vs-cervical-2017", "feng-kyphosis-correction-2018",
    ],
    "schroth-three-dimensional-exercises": [
      "ozdemir-schroth-2023",
    ],
    "diaphragmatic-breathing": [
      "csepregi-breathing-posture-2022", "eftekhari-breathing-kyphosis-2024",
    ],
    // Lumbar Spine and Core
    "core-stabilization-adim": [
      "calatayud-core-tolerability-2019", "puntumetakul-core-adim-2021",
      "guo-core-training-types-2025",
    ],
    "bird-dog": [
      "calatayud-core-tolerability-2019", "kim-lumbar-stabilization-emg-2016",
    ],
    "modified-curl-up-dead-bug": [
      "calatayud-core-tolerability-2019", "kim-lumbar-stabilization-emg-2016",
    ],
    // Shoulder Girdle
    "prone-horizontal-abduction-er": [
      "mendez-rebolledo-scapular-emg-2024", "andersen-scapular-intensity-2012",
      "reinold-rotator-cuff-emg-2004", "berckmans-scapular-emg-2021",
    ],
    "push-up-plus": [
      "andersen-scapular-intensity-2012", "kibler-scapular-rehab-2008",
      "escamilla-shoulder-rehab-2009",
    ],
    "external-rotation-0-abduction": [
      "mulroy-shoulder-sci-2020", "escamilla-shoulder-rehab-2009",
      "reinold-rotator-cuff-emg-2004", "hopewell-grasp-2021",
    ],
    // Hip and Pelvis
    "hip-abduction-strengthening": [
      "va-hip-knee-oa-2020", "cibulka-hip-oa-cpg-2017",
    ],
    "hip-flexor-hamstring-stretch": [
      "cibulka-hip-oa-cpg-2017", "moreside-hip-rom-2012",
    ],
    "pelvic-tilt-realignment": [
      "hayashi-pstr-hip-2022", "liu-lbp-exercise-2025",
    ],
    // Knee
    "quad-strengthening-slr-tke": [
      "va-hip-knee-oa-2020", "sharma-knee-oa-2021", "zeng-exercise-knee-oa-2022",
      "andersen-therapeutic-vs-heavy-2006", "gryzlo-knee-rehab-emg-1994",
      "escamilla-cruciate-loading-2012", "lawford-cochrane-knee-oa-2024",
    ],
    "neuromuscular-exercise-knee": [
      "sharma-knee-oa-2021", "zeng-exercise-knee-oa-2022", "roos-neuromuscular-2025",
      "flaxman-knee-synergies-2021", "yan-knee-oa-exercise-modalities-2025",
    ],
    "posterior-chain-strengthening": [
      "va-hip-knee-oa-2020", "zeng-exercise-knee-oa-2022",
    ],
    // Ankle and Foot
    "ankle-dorsiflexion-plantarflexion-band": [
      "wu-ankle-sprain-2025", "aafp-ankle-recovery-2025",
    ],
    "ankle-eversion-inversion-strengthening": [
      "wu-ankle-sprain-2025", "aafp-ankle-recovery-2025",
    ],
    "single-leg-balance-star-excursion": [
      "wu-ankle-sprain-2025", "zhang-ankle-instability-2025",
    ],
    // Existing exercises that gain new evidence links
    "scapular-retraction-exercise": [
      "cho-thoracic-vs-cervical-2017", "mendez-rebolledo-scapular-emg-2024",
      "berckmans-scapular-emg-2021", "johnson-trapezius-anatomy-1994",
    ],
    "resisted-external-rotation": [
      "mulroy-shoulder-sci-2020", "escamilla-shoulder-rehab-2009",
      "reinold-rotator-cuff-emg-2004", "lafrance-rotator-cuff-fitt-2024",
      "hopewell-grasp-2021",
    ],
    "clamshell": [
      "va-hip-knee-oa-2020", "cibulka-hip-oa-cpg-2017",
    ],
    "straight-leg-raise": [
      "va-hip-knee-oa-2020", "sharma-knee-oa-2021",
      "escamilla-cruciate-loading-2012", "andersen-therapeutic-vs-heavy-2006",
    ],
    "terminal-knee-extension": [
      "va-hip-knee-oa-2020", "sharma-knee-oa-2021",
      "gryzlo-knee-rehab-emg-1994", "escamilla-cruciate-loading-2012",
    ],
    "heel-raise": [
      "wu-ankle-sprain-2025", "zeng-exercise-knee-oa-2022",
    ],
  };

  let targetedCount = 0;
  for (const [exerciseSlug, sourceSlugs] of Object.entries(exerciseSourceMap)) {
    const exercise = await prisma.exercise.findUnique({ where: { slug: exerciseSlug } });
    if (!exercise) {
      console.warn(`    ⚠ Exercise not found: ${exerciseSlug}`);
      continue;
    }
    for (const sourceSlug of sourceSlugs) {
      const source = await prisma.researchSource.findUnique({ where: { slug: sourceSlug } });
      if (!source) {
        console.warn(`    ⚠ Source not found: ${sourceSlug}`);
        continue;
      }
      await linkSource(source.id, "Exercise", exercise.id, "exerciseId", "Region-specific evidence");
      targetedCount++;
    }
  }

  logCount("targeted evidence links", targetedCount);
}
